name: Compile script

on:
  [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip
    - name: Compile
      run: |
        chmod 777 ./build.sh
        mkdir -p bin
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=aarch64-linux-android31-clang++ ./build.sh bin/compiled_script_arm64
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=armv7a-linux-androideabi31-clang++ ./build.sh bin/compiled_script_arm
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=i686-linux-android31-clang++ ./build.sh bin/compiled_script_x86
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=x86_64-linux-android31-clang++ ./build.sh bin/compiled_script_x64
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: compiled-script
        path: bin
